---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: Installation of python3, pip, and Java packages for Ubuntu
    apt:
      name:
        - python3
        - pip
        - openjdk-8-jdk
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Installation of python3, pip, and Java packages for CentOS
    dnf:
      name:
        - python3
        - python3-pip
        - java-1.8.0-openjdk
      state: latest
    when: ansible_distribution == "CentOS"

